version: '3.9'
services:
  realtime:
    build: .
    container_name: lesson20-realtime
    environment:
      - PORT=3001
      - REDIS_URL=redis://redis:6379
    ports:
      - "3001:3001"
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    container_name: lesson20-redis
    ports:
      - "6379:6379"
